### ISSUE TITLE
Having a issue to generate .tmp folders

### ISSUE THREAD

**Issue by antiperfectclub** [danielstern/react-express-examplar#1]
Hi Dan, 

Thanx for amazing tuts from PluralSight. I have been so far stuck on very beginning part lol (mostly comes from the crushes of modules)

on gulp.js file, I have written :

var gulp = require('gulp');

var browserSync = require('browser-sync');
var browserify = require('browserify');

var LiveServer = require('gulp-live-server');
var reactify = require('reactify');
var source = require('vinyl-source-stream');

gulp.task('live-server',function(){
  var server = new LiveServer('server/main.js');
  server.start();
});

gulp.task('bundle',function(){
 return browserify({
  entries: 'app/main.jsx',
  debug: true,
 })
 .transform(reactify)
 .bundle()
 .pipe(source('app.js'))
 .pipe(gulp.dest('./.tmp'));
});
gulp.task('serve', ['live-server'], function() {
  browserSync.init(null, {
    proxy: "http://localhost:7777",
    port: 9001
  });
});

and on command shell, gulps throws errorevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module './dispatcher.js' from '/Users/ChloeGyuriKim/Desktop/Webproject/React/react-express-examplar/app'
    at /Users/ChloeGyuriKim/Desktop/Webproject/React/react-express-examplar/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/ChloeGyuriKim/Desktop/Webproject/React/react-express-examplar/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/ChloeGyuriKim/Desktop/Webproject/React/react-express-examplar/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/ChloeGyuriKim/Desktop/Webproject/React/react-express-examplar/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)

and I haven't succeeded to generate .tmp folders. 

Would you advise me to solve this pain?

I look forward to hear from you soon.

**Comment by danielstern** [comment]
Hey Chloe.

I've had a look and I'm not sure exactly what the issue is.

I recommend you checkout the closest Git branch with the work completed and keep working from there. I think this one might be close:

https://github.com/danielstern/react-express-examplar/tree/react-components-begin. If this is too early, please check out the appropriate branch.

DS
